import React from "react";
import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'

const Div = styled('div')({
  minHeight: '100vh',
  padding: '0 0.5rem',
  display: 'flex',
  flexDirection: 'column',
  justifyContent: 'center',
  alignItems: 'center',
  height: '100vh',
})

const Main = styled('main')({
  padding: '5rem 0',
  flex: '1',
  display: 'flex',
  flexDirection: 'column',
  justifyContent: 'center',
  alignItems: 'center',
  margin: 0,
  fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif',
})

const Paragraph = styled('p')({
  fontSize: '2rem',
})

const Title = styled('h1')({
  fontSize: '3rem',
})

const Home: NextPage = () => {
  return (
    <Div>
      <Head>
        <title>Template NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main >
        <Title>NextJS + TypeScript + React Components</Title>

        <section>
          <Paragraph>Feito com &#10084; por <a href="https://https://github.com/NathanFirmo" target="_blank" rel="noopener noreferrer"><span>Nathan Firmo</span></a>.</Paragraph>
        </section>
      </Main>
    </Div>
  )
}

export default Home
