import React from "react";
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Template NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span>Next + TypeScript + Docker + Prisma</span>
        </h1>

        <section>
          <p className={styles.mainParagraph}>Feito com &#10084; por <a href="https://https://github.com/NathanFirmo" target="_blank" rel="noopener noreferrer"><span>Nathan Firmo</span></a>.</p>
        </section>
      </main>
    </div>
  )
}

export default Home
